services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: survey
      POSTGRES_PASSWORD: survey
      POSTGRES_DB: survey
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "survey"]
      interval: 10s
      retries: 5

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://survey:survey@db:5432/survey
      SECRET_KEY: "CHANGE_ME"
    volumes: [./backend:/app]
    depends_on:
      db: {condition: service_healthy}

  frontend:
    build: ./frontend
    ports: ["3000:80"]
    depends_on: [backend]

volumes:
  pgdata:
